# Generated by Django 4.1.7 on 2023-05-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_audio_patient_remove_audio_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='audio',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
