export const meetings: Meeting[] = [
    {
        name: 'Monday 4/12',
        startDate: new Date(2023, 4, 12, 9, 30, 12),
        endDate: new Date(2023, 4, 12, 10, 45, 31),
        summary: 'This text is going to be generated by GPT3'
    },
    {
        name: 'Group Meeting',
        startDate: new Date(2023, 4, 12, 17, 30, 12),
        endDate: new Date(2023, 4, 12, 17, 45, 31),
        summary: 'This text is going to be generated by GPT3'
    },
    {
        name: 'Friday 4/14',
        startDate: new Date(2023, 4, 14, 9, 30, 12),
        endDate: new Date(2023, 4, 14, 10, 45, 31),
        summary: 'This text is going to be generated by GPT3'
    },
    {
        name: 'Monday 4/12',
        startDate: new Date(2023, 4, 12, 9, 30, 12),
        endDate: new Date(2023, 4, 12, 10, 45, 31),
        summary: 'This text is going to be generated by GPT3'
    },
]